### ISSUE TITLE
transfrom和绝对定位的动画性能对比

### ISSUE THREAD

**Issue by moumoutang** [moumoutang/moumoutang.github.io#6]
页面布局如下：
```html
  <div class="outter">
    <div id="target" class="target"></div>
    <div class="other"></div>
  </div>
```
```css
    .outter{
      position: relative;
      height: 500px;
      width: 500px;
      border: 1px solid;
    }
    .target{
      position: absolute;
      top: 0;
      left: 0;
      height: 200px;
      width: 200px;
      background-color: red;
      -webkit-animation: move 2s infinite;
    }
    .other{
      position: absolute;
      height: 100px;
      width: 100px;
      border: 2px solid green;
    }
```
其中animation的实现分为两种：
```css
    @-webkit-keyframes move {
      50% { 
        top: 100px;
        left: 100px;
      }
    }
    @-webkit-keyframes move {
      50% { 
        transform: translate(100px, 100px);
      }
    }
```
那么对于两种动画，看起来表现是一致的，哪种更好呢？
相信大部分人都会说第二种
那为什么呢？
