### ISSUE TITLE
css tips

### ISSUE THREAD

**Issue by moumoutang** [moumoutang/moumoutang.github.io#7]
- 清除浮动
```css
// 普通浏览器下
.clearfix:before,
.clearfix:after {
    content: " "; /* 1 */
    display: table; /* 2 */
}
.clearfix:after {
    clear: both;
}
/**
* IE 6/7下使用
* 通过触发hasLayout实现包含浮动
**/
.clearfix {
    *zoom: 1;
}
```

-
